### PR TITLE
Improve various  things.

### PR DESCRIPTION
**Pull request by Ar37-rs**

### CODE REVIEW

**Comment by MoAlyousef** [comment]
Hi.
Thanks for the PR and the improvements. Especially the DpiScaling. On my windows machine, since I run a non-custom scaling, I found that I still had to add the `app::set_screen_scale(window.screen_num(), 1.);` in the painter code, even when it's then overriden by the DpiScaling, for some reason it fixes things for me.

**Comment by Ar37-rs** [comment]
@MoAlyousef thanks, but current problem is mouse wheel still can't zoom on plot area, not sure why.

**Comment by MoAlyousef** [comment]
I can’t test now, but maybe this line in lib.rs
https://github.com/fltk-rs/fltk-egui/blob/7c0d8c9403d14aa9351fe7cf1a6d02d1bf145e24/src/lib.rs#L215

Should take a event_dx() and event_dy() instead of event_x() and event_y()

**Comment by Ar37-rs** [comment]
@MoAlyousef yup, will be fixed in the latest PR.

**Pull request merged**
