### PR TITLE
 Redesign image feature and visual scaling. 

### PR DESCRIPTION
**Pull request by Ar37-rs**
* don't use egui_extras crates for image
* bring back visual scaling (DPI Scaling like, but way more proper)

### CODE REVIEW

**Comment by MoAlyousef** [comment]
Thank you

**Comment by MoAlyousef** [comment]
It seems usync requires unstable Rust. I would prefer to replace it with std Mutex or some other Mutex.

**Comment by MoAlyousef** [comment]
Would you say it's time for a 0.6 release?

**Comment by Ar37-rs** [comment]
@MoAlyousef for backward compatibility doesn't matter i think using std mutex. oops, i don't know the MSRV of usync is 1.59 in case. the rest sound good to me it's time for release

**Pull request merged**
